import os
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

objs = Glob('*.cpp') + Glob('*.c')
group = DefineGroup('solution_application', objs, depend = ['PKG_USING_NES'], CPPPATH = [cwd])

Return('group')
