CONFIG_RT_USING_DFS_ELMFAT=y
CONFIG_RT_MAIN_THREAD_STACK_SIZE=4096
CONFIG_RT_USING_MEMHEAP=y
CONFIG_AUDIO=y
CONFIG_AUDIO_LOCAL_MUSIC=y
CONFIG_PKG_USING_LITTLEVGL2RTT=y
# CONFIG_LV_USING_EXT_RESOURCE_MANAGER is not set
CONFIG_LV_FONT_MONTSERRAT_16=y
CONFIG_LV_FONT_MONTSERRAT_20=y
CONFIG_LV_FONT_MONTSERRAT_24=y
CONFIG_LV_FONT_MONTSERRAT_28=y
CONFIG_LV_FONT_MONTSERRAT_36=y
CONFIG_PKG_USING_NES=y
CONFIG_NES_SINGLE_APP=y
