from building import *
import rtconfig
import os

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

if GetDepend('PKG_USING_NES'):
    objs = Glob('*.cpp')+Glob('*.c')

#include all subfolder
#for d in list:
#    path = os.path.join(cwd, d)
#    if os.path.isfile(os.path.join(path, 'SConscript')):
#        objs = objs + SConscript(os.path.join(d, 'SConscript'))

objs.extend(SConscript(os.path.join(cwd, 'rtthread/SConscript'), variant_dir="rtthread", duplicate=0))

group = DefineGroup('nes', objs, depend = ['PKG_USING_NES'], CPPPATH = [cwd])

Return('group')
