from building import *
import rtconfig
import os

src = []
inc = []
cwd = GetCurrentDir() # get current dir path

src=Glob('*.c')+Glob('*.cpp')
inc+=[cwd]
inc+=[cwd+'/rtthread']

group = DefineGroup('infoNES', src, depend = ['PKG_USING_LITTLEVGL2RTT'], CPPPATH = inc)
for d in os.listdir(cwd):
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))
Return('group')